# Generated by Django 3.2.7 on 2021-10-02 08:24

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created At')),
                ('due_date', models.DateField(
                    default=core.models.get_due_date,
                    verbose_name='Due Date')),
                ('quantity', models.IntegerField(
                    verbose_name='Quantity')),
                ('returned', models.BooleanField(
                    default=False, verbose_name='Is Returned')),
                ('returned_at', models.DateTimeField(
                    blank=True, null=True, verbose_name='Returned At')),
                ('extra_charge', models.DecimalField(
                    decimal_places=2,
                    max_digits=6,
                    verbose_name='Extra Charge')),
                ('amount', models.DecimalField(
                    decimal_places=2, max_digits=6, verbose_name='Amount')),
                ('movie', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='core.movie')),
                ('rented_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rent',
                'verbose_name_plural': 'Rents',
            },
        ),
    ]
