# Generated by Django 3.2.7 on 2021-10-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieimage',
            name='image',
            field=models.ImageField(
                upload_to='movies/images/', verbose_name='Image'),
        ),
    ]
