# Generated by Django 3.2.7 on 2021-10-04 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_movieimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieimage',
            name='movie',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='movies',
                to='core.movie'),
        ),
    ]
