# Generated by Django 3.2.7 on 2021-10-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211005_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCharge',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(
                    decimal_places=2,
                    default=0.0,
                    max_digits=8,
                    verbose_name='Amount')),
                ('is_paid', models.BooleanField(
                    default=False, verbose_name='Is paid?')),
                ('paid_at', models.DateTimeField(
                    blank=True, null=True, verbose_name='Paid at')),
            ],
        ),
        migrations.RemoveField(
            model_name='rent',
            name='extra_charge',
        ),
        migrations.AddField(
            model_name='rent',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is paid?'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='due_date',
            field=models.DateField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='returned_at',
            field=models.DateField(
                blank=True, null=True, verbose_name='Returned At'),
        ),
    ]
