# Generated by Django 3.2.7 on 2021-10-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211008_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extracharge',
            options={
                'verbose_name': 'Extra charge',
                'verbose_name_plural': 'Extra charges',
            },
        ),
        migrations.AddField(
            model_name='rent',
            name='payment_reference',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Payment reference'
            ),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
