# Generated by Django 3.2.7 on 2021-10-11 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_rent_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='payment_url',
            field=models.URLField(
                blank=True, null=True, verbose_name='Payment url'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rented_by',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
