# Generated by Django 3.2.7 on 2021-10-11 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211011_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracharge',
            name='rent',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.rent'),
        ),
    ]
